# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTVnJ-Rp9TkmcWz-Y75-UQmQ-UgNQH7l
"""

def recebeNome():
    return input("Insira seu nome completo: ")

def recebeAnoNascimento():
    while True:
        ano = input("Insira seu ano de nascimento (entre 1922 e 2021): ")
        if ano.isdigit():
            ano = int(ano)
            if 1922 <= ano <= 2021:
                return ano
            else:
                print("Ano fora do intervalo permitido. Tente novamente.")
        else:
            print("Opçao inválida. Por favor, insira um número.")

def calcularIdade(anoNascimento):
    anoAtual = 2022
    return anoAtual - anoNascimento

def main():
    nome = recebeNome()
    anoNascimento = recebeAnoNascimento()
    idade = calcularIdade(anoNascimento)

    print(f"{nome}, você completou ou irá completar {idade} anos em 2022.")

if __name__ == "__main__":
    main()